"""SubAgent: worker agent with Tree-of-Thought reasoning and LoRA slot."""
from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from memory.graph import MemoryGraph
from memory.retrieval import Retriever
from solver.solver import Solver
from agents.tree_of_thought import TreeOfThought, ThoughtBranch
from agents.knowledge_transfer import LoRAAdapter
from agents.teacher import SubTask

logger = logging.getLogger(__name__)


@dataclass
class SubAgentResult:
    """Result returned by a SubAgent after solving a subtask."""

    task_id: str
    success: bool
    selected_branch: ThoughtBranch
    all_branches: List[ThoughtBranch]
    reasoning_trace: List[str]
    duration: float


class SubAgent:
    """Worker agent with Tree-of-Thought reasoning and LoRA adapter slot.

    Each SubAgent owns a slot for a LoRA adapter that can be hot-injected by
    the KnowledgeTransferManager when the agent is stuck.

    When a :class:`~models.model_registry.ModelRegistry` is provided, the MoE
    *subagent* role model is used to generate reasoning and answers for each
    Tree-of-Thought branch.  Without a registry the class falls back to the
    Solver-based approach so that existing tests continue to pass.
    """

    def __init__(
        self,
        agent_id: int,
        solver: Solver,
        graph: MemoryGraph,
        retriever: Retriever,
        tot_engine: TreeOfThought,
        lora_adapter: Optional[LoRAAdapter] = None,
        registry: Optional[Any] = None,
    ) -> None:
        self.agent_id = agent_id
        self.solver = solver
        self.graph = graph
        self.retriever = retriever
        self.tot_engine = tot_engine
        self.lora_adapter = lora_adapter
        self.registry = registry

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def solve(
        self,
        subtask: SubTask,
        predecessor_results: Optional[Dict[str, Any]] = None,
    ) -> SubAgentResult:
        """Solve a subtask using Tree-of-Thought exploration.

        1. Retrieve relevant skills from memory graph.
        2. Generate thought branches (binary tree).  When a registry is
           available, each branch answer is generated by the MoE subagent LLM
           (multiple temperature-sampled completions).
        3. Score branches using GIGPO (if available in ToT engine).
        4. Select best branch at each level.
        5. If both branches bad → signal for knowledge transfer via low confidence.
        """
        t0 = time.time()
        trace: List[str] = []

        # Build context from subtask + predecessor results
        context = dict(subtask.context)
        if predecessor_results:
            context["predecessor_results"] = predecessor_results
        context["problem"] = subtask.context.get("problem", {
            "statement": subtask.description,
            "topic": context.get("topic", "general"),
            "domain": context.get("domain", "math"),
            "answer_spec": context.get("answer_spec", {}),
        })

        # Stage 1: retrieve relevant skills
        retrieved = self.retriever.retrieve(
            problem_text=subtask.description,
            topic=context.get("topic", "general"),
            domain=context.get("domain", "math"),
            top_k=5,
        )
        context["retrieved_skills"] = [item.skill_node for item in retrieved]
        trace.append(f"Retrieved {len(retrieved)} skill(s)")

        # Stage 2: Tree-of-Thought exploration
        # When a registry is available, enrich each branch with LLM output
        branches = self.tot_engine.explore(
            problem_text=subtask.description,
            context=context,
            solver=self.solver,
            graph=self.graph,
        )
        trace.append(f"ToT generated {len(branches)} branch(es)")

        if self.registry is not None:
            branches = self._enrich_branches_with_llm(branches, subtask, context)
            trace.append("Enriched branches with MoE LLM output")

        # Stage 3: select best branch
        best = self.tot_engine.select_best(branches)
        trace.append(f"Selected branch '{best.branch_id}' (confidence={best.confidence:.3f})")

        success = bool(best.answer and best.confidence > 0.2)
        duration = time.time() - t0

        return SubAgentResult(
            task_id=subtask.task_id,
            success=success,
            selected_branch=best,
            all_branches=branches,
            reasoning_trace=trace,
            duration=duration,
        )

    def _enrich_branches_with_llm(
        self,
        branches: List[ThoughtBranch],
        subtask: SubTask,
        context: Dict[str, Any],
    ) -> List[ThoughtBranch]:
        """Replace branch answers with LLM-generated completions.

        Each branch is sampled with a different temperature so that the
        diversity of ToT is preserved.
        """
        from models.prompts import SUBAGENT_SOLVE_PROMPT

        enriched: List[ThoughtBranch] = []
        temperatures = [0.7 + i * 0.1 for i in range(len(branches))]

        skills = context.get("retrieved_skills", [])
        ctx_str = ""
        if skills:
            ctx_str = "Skills: " + ", ".join(s.get("label", "?") for s in skills[:3])

        for branch, temp in zip(branches, temperatures):
            try:
                prompt = SUBAGENT_SOLVE_PROMPT.format(
                    subtask=subtask.description[:200],
                    context=ctx_str or "None",
                )
                raw = self.registry.generate(
                    "subagent",
                    prompt,
                    max_new_tokens=512,
                    temperature=temp,
                )
                # Extract last non-empty line as answer
                lines = [l.strip() for l in raw.splitlines() if l.strip()]
                llm_answer = lines[-1] if lines else branch.answer
                enriched.append(ThoughtBranch(
                    branch_id=branch.branch_id,
                    reasoning=raw[:500],
                    answer=llm_answer,
                    confidence=min(1.0, branch.confidence + 0.1),
                    depth=branch.depth,
                ))
            except Exception as exc:
                logger.debug("SubAgent LLM enrichment failed for branch %s: %s", branch.branch_id, exc)
                enriched.append(branch)

        return enriched if enriched else branches

    def inject_lora(self, adapter: LoRAAdapter) -> None:
        """Hot-inject a LoRA adapter into this agent's model."""
        self.lora_adapter = adapter

    def retry_with_hint(
        self,
        subtask: SubTask,
        hint: str,
    ) -> SubAgentResult:
        """Retry solving with a golden thought hint from the Teacher.

        When a registry is available, the hint is included in the LLM prompt.
        Otherwise, falls back to re-running ToT with the hint in context.
        """
        t0 = time.time()
        trace: List[str] = [f"Retrying with golden thought hint (len={len(hint)})"]

        # --- LLM path ---
        if self.registry is not None:
            try:
                from models.prompts import SUBAGENT_SOLVE_WITH_HINT_PROMPT

                skills = subtask.context.get("retrieved_skills", [])
                ctx_str = ""
                if skills:
                    ctx_str = "Skills: " + ", ".join(s.get("label", "?") for s in skills[:3])

                prompt = SUBAGENT_SOLVE_WITH_HINT_PROMPT.format(
                    subtask=subtask.description[:200],
                    hint=hint[:300],
                    context=ctx_str or "None",
                )
                raw = self.registry.generate(
                    "subagent",
                    prompt,
                    max_new_tokens=512,
                    temperature=0.6,
                )
                lines = [l.strip() for l in raw.splitlines() if l.strip()]
                llm_answer = lines[-1] if lines else ""
                branch = ThoughtBranch(
                    branch_id=f"retry_llm_{subtask.task_id[:8]}",
                    reasoning=raw[:500],
                    answer=llm_answer,
                    confidence=0.8,
                    depth=1,
                )
                trace.append(f"LLM retry answer: {llm_answer[:60]}")
                return SubAgentResult(
                    task_id=subtask.task_id,
                    success=bool(llm_answer),
                    selected_branch=branch,
                    all_branches=[branch],
                    reasoning_trace=trace,
                    duration=time.time() - t0,
                )
            except Exception as exc:
                logger.warning("SubAgent.retry_with_hint LLM path failed: %s", exc)

        # --- Heuristic fallback ---
        context = dict(subtask.context)
        context["golden_hint"] = hint
        context["problem"] = subtask.context.get("problem", {
            "statement": subtask.description,
            "topic": context.get("topic", "general"),
            "domain": context.get("domain", "math"),
            "answer_spec": context.get("answer_spec", {}),
        })

        retrieved = self.retriever.retrieve(
            problem_text=subtask.description + " " + hint,
            topic=context.get("topic", "general"),
            domain=context.get("domain", "math"),
            top_k=5,
        )
        context["retrieved_skills"] = [item.skill_node for item in retrieved]
        trace.append(f"Retrieved {len(retrieved)} skill(s) with hint context")

        branches = self.tot_engine.explore(
            problem_text=subtask.description,
            context=context,
            solver=self.solver,
            graph=self.graph,
        )
        best = self.tot_engine.select_best(branches)
        # Boost confidence slightly when a hint was provided
        boosted_confidence = min(1.0, best.confidence + 0.15)
        boosted_branch = ThoughtBranch(
            branch_id=best.branch_id,
            reasoning=best.reasoning,
            answer=best.answer,
            confidence=boosted_confidence,
            depth=best.depth,
        )
        trace.append(f"Retry best branch conf={boosted_confidence:.3f}")

        success = bool(boosted_branch.answer and boosted_confidence > 0.2)
        return SubAgentResult(
            task_id=subtask.task_id,
            success=success,
            selected_branch=boosted_branch,
            all_branches=branches,
            reasoning_trace=trace,
            duration=time.time() - t0,
        )
